<?php
defined('ABSPATH') || exit;

/** Shared visitor identifier contract for frontend and future WP AIgent modules. */
class WP_AIGent_Visitor_Identity {
    public const CONVERSATION_META_KEY = 'conversation_visitor_id';

    /** Accept only RFC 4122 version 4 UUIDs generated by a cryptographic browser API. */
    public static function is_valid(string $visitor_id): bool {
        return (bool) preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i', $visitor_id);
    }
}
